version = 0.1
[default.deploy.parameters]
stack_name = "data-caching-service-api"
resolve_s3 = true
s3_prefix = "data-caching-service-api"
region = "eu-north-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
